{% set name = "nbstripout" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62f1b1fe9c7c298061089fd9bd5d297eb6209f7fbef0758631dbe58d38fc828f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nbstripout = nbstripout:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - nbformat

test:
  requires:
    - nbformat
  imports:
    - nbstripout
  commands:
    - nbstripout --help

about:
  home: https://github.com/kynan/nbstripout
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'strip output from Jupyter and IPython notebooks'
  description: |
    Opens a notebook, strips its output, and writes the outputless version to the
    original file.

    Useful mainly as a git filter or pre-commit hook for users who don't want to
    track output in VCS.

    This does mostly the same thing as the `Clear All Output` command in the
    notebook UI.
  doc_url: https://pypi.org/project/nbstripout/
  dev_url: https://github.com/kynan/nbstripout

extra:
  recipe-maintainers:
    - kynan
